### ISSUE TITLE
"405 Method Not Allowed" with Multipart upload

### ISSUE THREAD

**Issue by zzzplayer** [timkay/aws#44]
So I was uploading a 15 GB file (and alternatively, a 6.5GB file) with the following sample command

```
~/aws put backup_bucket/diskimg.raw /mnt/img/diskimg.raw
```

it was able to upload the file parts and they show up in the bucket, but the command always shows a "405 Method Not Allowed" in the end.

For the 15GB file, it would upload 2~3 files of 5 GB each, then it shows a "405 Method Not Allowed". (the file parts along with the upload ids would remain in the bucket).

I initially think it's a permission issue, but after checking, I don't think they are.

The bucket grants full rights to the bucket owner and any authenticated user. Bucket policy is in the default setting and empty. CORS policy is in the default setting and shouldn't be applicable to me since I'm runing the command from an EC2 instance within the same account. Also, I'm not using any IAM roles (they are all empty).

In addition, and most importantly, I was able to upload any files less than 5 GB in size, as always, to the same bucket.

The aws command was already the latest version, v1.80.

**Comment by Sigafoos** [comment]
Because this is the _only place_ I was able to find where someone had solved this issue:

"405 Method Not Allowed" as a response to a CompleteMultipartUpload request could be (and was, in both this case and mine) because the IAM user does not have EC2 permissions. This is not documented anywhere, and doesn't really make sense since you're dealing with S3 and not EC2 (though it seems to be because EC2 is used to combine the parts).

Thank you for this fix, and I'm sorry for commenting on a six-and-a-half-year old issue.

**Comment by mecheverri** [comment]
In a web search for information about the 405 response, this page ranks pretty high.  Because of that, I'm going to post what I've found here too, in the hopes it might save someone else hours of wasted time.

I was getting 405's from my CompleteMultipart responses.  After much searching and experimentation, I happened to find that changing the querystring parameter from `UploadId` to `uploadId` changed the response from 405 to 400.  After more experimenting, I found the following:
- The UploadPart requests must be made with parameters `partNumber` and `uploadId`, even though requests that use capitalized parameters succeed.  Otherwise, the CompleteMultipart request will fail with a 400 ("InvalidPart").
- The CompleteMultipart request must be made with `uploadId`.

Amazon's documentation (e.g. https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html ) is no help here:  It contains examples using both capitalized and non-capitalized parameters.  Obviously, this is an undocumented feature. No wonder it's been hard to reproduce.

**Comment by Sigafoos** [comment]
Also, it appears that my fix has not actually fixed anything. I left my code for a week or so while I worked on something else and when I came back it was still broken. I’m no longer on that project, so I’m not going to be of any help now (although, since I gave bad information, it’s possible me not contributing will actually be better for people in the long run)

**Comment by timkay** [comment]
Dan, thanks for the information. I'll take a look when I get a chance.
